// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWQA1wzsB7xOA2waQTQbwjIOO5VXPOpHQ',
    appId: '1:92686701696:web:42ce036fd843e1f9d34265',
    messagingSenderId: '92686701696',
    projectId: 'cardrivetest-5f012',
    authDomain: 'cardrivetest-5f012.firebaseapp.com',
    storageBucket: 'cardrivetest-5f012.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW30P1rWyOR3HDu8-uFjBinO-uDUb3qDw',
    appId: '1:92686701696:android:bb73e1bb4ed7eb16d34265',
    messagingSenderId: '92686701696',
    projectId: 'cardrivetest-5f012',
    storageBucket: 'cardrivetest-5f012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5q31-Cjqdn6hGNuFX-BPjkbxYRI6BqbM',
    appId: '1:92686701696:ios:e93b0a5aa7767febd34265',
    messagingSenderId: '92686701696',
    projectId: 'cardrivetest-5f012',
    storageBucket: 'cardrivetest-5f012.appspot.com',
    iosClientId: '92686701696-aqp4ojl17sb7ra0aciqft2nlnpn2dnjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.car',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5q31-Cjqdn6hGNuFX-BPjkbxYRI6BqbM',
    appId: '1:92686701696:ios:e93b0a5aa7767febd34265',
    messagingSenderId: '92686701696',
    projectId: 'cardrivetest-5f012',
    storageBucket: 'cardrivetest-5f012.appspot.com',
    iosClientId: '92686701696-aqp4ojl17sb7ra0aciqft2nlnpn2dnjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.car',
  );
}
